name: Release AddOn

#on: [push]
on:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - '.github/**'
env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@v2
        with:
          args: -p 993748 -w 26709 -a L6JDoxGv
