name: Packager

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  packager:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.EVOKER_TOKEN }}
      DISCORD_WEBHOOK: ${{ env.WEBHOOK_URL }}
  
    steps:
      - name: Print secrets
        run: |
          echo "CF_API_KEY: $CF_API_KEY"
          echo "WOWI_API_TOKEN: $WOWI_API_TOKEN"
          echo "WAGO_API_TOKEN: $WAGO_API_TOKEN"
          echo "GITHUB_OAUTH: $GITHUB_OAUTH"
          echo "DISCORD_WEBHOOK: $DISCORD_WEBHOOK"

      - name: Discord notification          
        uses: Ilshidur/action-discord@master
        with:
          args: 'EvokerAug'
