name: Packager

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  packager:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
          
      - name: Update option files
        if: always()
        run: EvokerAug.toc

      - name: Package 
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.EVOKER_TOKEN }}
