name: Packager

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  packager:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.EVOKER_TOKEN }}
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@master
        with:
          args: -p 993748 -w 26709 -a L6JDoxGv


      - name: Upload to Github Actions
        uses: actions/upload-artifact@v4
        with:
          name: EvokerAug
          path: .release/*.zip

      - name: Send a message to Discord if meets a failure
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
        if: failure()
