name: Packager

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  packager:
    runs-on: ubuntu-latest

    steps:
      - name: Print secrets
        run: |
          echo "CF_API_KEY: ${{ secrets.CF_API_KEY }}"
          echo "WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}"
          echo "WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}"
          echo "GITHUB_OAUTH: ${{ secrets.EVOKER_TOKEN }}"
          echo "DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}"
